version: "3.9"
   
services:
  jupyter:
    image: custom_julab:test
    ports:
      - "10000:8888"
    #volumes:
    #  - ./notebooks:/home/jovyan/
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password='password'"
