version: "3.9"
   
services:
  jupyter:
    image: custom_julab:test
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password='password' --NotebookApp.allow_origin='*' --NotebookApp.allow_remote_access='true' --NotebookApp.port=8888 --NotebookApp.base_url=/jupyter/"
    expose:
      - 8888
    networks:
      - jupyter_net

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    networks:
      - jupyter_net

networks:
  jupyter_net:
    driver: bridge
